#!/bin/bash -e

eval "$(cli-shezargs $@)"

if jsaws-build-block "node-utils2" "Node-based Utilities for platform"; then

  npm install -g tap-difflet
  npm install -g yaml-cli
  npm install -g iponmap
  npm install -g pm2

  jsaws-build-block "node-utils2" "done"
fi

