#!/bin/bash -e

eval "$(cli-shezargs $@)"

if jsaws-build-block "node-utils2" "Node-based Utilities for platform"; then

  yarn global add tap-difflet
  yarn global add yaml-cli
  yarn global add iponmap
  yarn global add pm2

  jsaws-build-block "node-utils2" "done"
fi

