#!/bin/bash -e

sudo DEBIAN_FRONTEND=noninteractive sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
                                         apt-transport-https \
                                         ca-certificates \
                                         software-properties-common \
                                         curl

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo DEBIAN_FRONTEND=noninteractive sudo apt-key fingerprint '0EBFCD88'

sudo DEBIAN_FRONTEND=noninteractive sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo DEBIAN_FRONTEND=noninteractive sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -y docker-ce

sudo usermod -a -G docker $USER

