#!/bin/bash -e

# https://inthecheesefactory.com/blog/how-to-setup-private-maven-repository/en
# https://jeroenmols.com/blog/2015/08/06/artifactory/

# Here is how to push to jcenter
# https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

sudo DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:webupd8team/java
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y oracle-java8-installer

#gpg --keyserver pgpkeys.mit.edu --recv-key 6B219DCCD7639232
#gpg -a --export 6B219DCCD7639232 | sudo apt-key add -
#apt-get update

mkdir -p ~/zz_packages && cd $_
aws s3 cp s3://mobilewebprint-deploy/buildout/packages/jfrog-artifactory-oss-5.3.0.deb ./
sudo DEBIAN_FRONTEND=noninteractive dpkg -i jfrog-artifactory-oss-5.3.0.deb

sudo service artifactory start


